apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: personal-site
spec:
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
        - name: personal-site
          image: ghcr.io/danielpower/personal-site:main@sha256:86d50c25d6acfd43875d79d5bbe05ec74cb5932cf6b3fe27c94a6b226c0e59db
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PROMETHEUS_URL
              value: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 3000
